export const strets = [
  {id: 1, name: 'пр. Независимости, 4', favorite: false},
  {id: 2, name: 'ул. Бобруйская, 5', favorite: false},
  {id: 3, name: 'ул. Ленинградская, 8', favorite: false},
  {id: 4, name: 'ул. Ленинградская, 16', favorite: false},
  {id: 5, name: 'ул. К.Маркса, 31', favorite: false},
  {id: 6, name: 'ул. К.Маркса, 31', favorite: false},
  {id: 7, name: 'ул. Ленинградская, 14', favorite: false},
  {id: 8, name: 'Курчатоваб 8', favorite: false},
  {id: 9, name: 'Курчатоваб 6', favorite: false},
  {id: 10, name: 'str', favorite: false},
  {id: 11, name: 'пр. Независимости, 4', favorite: false},
  {id: 12, name: 'ул. Бобруйская, 5', favorite: false},
  {id: 13, name: 'ул. Ленинградская, 8', favorite: true},
  {id: 14, name: 'ул. Ленинградская, 16', favorite: false},
  {id: 15, name: 'ул. К.Маркса, 31', favorite: false},
  {id: 16, name: 'ул. К.Маркса, 31', favorite: true},
  {id: 17, name: 'ул. Ленинградская, 14', favorite: false},
  {id: 18, name: 'Курчатоваб 8', favorite: false},
  {id: 19, name: 'Курчатоваб 6', favorite: false},
  {id: 20, name: 'str', favorite: false},
  {id: 21, name: 'пр. Независимости, 4', favorite: false},
  {id: 22, name: 'ул. Бобруйская, 5', favorite: false},
  {id: 23, name: 'ул. Ленинградская, 8', favorite: false},
  {id: 24, name: 'ул. Ленинградская, 16', favorite: false},
  {id: 25, name: 'ул. К.Маркса, 31', favorite: false},
  {id: 26, name: 'ул. К.Маркса, 31', favorite: false},
  {id: 27, name: 'ул. Ленинградская, 14', favorite: false},
  {id: 28, name: 'Курчатоваб 8', favorite: false},
  {id: 29, name: 'Курчатоваб 6', favorite: true},
  {id: 30, name: 'str', favorite: true},
];
